# Generated by Django 5.1.1 on 2024-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
