# Generated by Django 5.1.1 on 2024-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(),
        ),
    ]
